[package]
name = "RustCraft"
version = "0.1.1"
edition = "2021"

[features]
shipping = []


[dependencies]
async-std = "1.12.0"
bytemuck = { version = "1.14.1", features = ["derive"] }
nalgebra = "0.32.3"
wgpu = "0.19.1"
winit = "0.29.10"
