[package]
name = "GameEngine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.opencl3]
version = "0.9.5"
features = ["CL_VERSION_3_0"]